version: "3"
services:
  server:
    #image: leem_01/karten-fuer-alle
    build: .
    mem_limit: 128m
    ports:
      - "3000:3000"
    links:
      - mongo
    networks:
      - default
    #//https://nickjanetakis.com/blog/docker-tip-30-running-docker-compose-from-a-different-directory
    # build:
    #   context: .
    #   dockerfile: Dockerfile.dev
    volumes:
      - ../../env:/app/env
    #   - /app/node_modules
    #   - .:/app

    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    restart: always
  # tests:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /app/node_modules
  #     - .:/app
  #   command: ["npm","run","test"]
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    networks:
      - default
    #environment:
     # MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: example
    restart: always
    mem_limit: 128m


  mongo-express:
    image: mongo-express
    container_name: mongo-express
    mem_limit: 128m
    restart: always
    ports:
      - 8081:8081
    environment:
      #ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - default